<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Troovon</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="robots" content="noindex, nofollow">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="/assets/library/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/assets/stylesheets/admin/style-admin.css">
  <link rel="stylesheet" href="/assets/stylesheets/custom-theme/jquery-ui-1.8.16.custom.css">
  <link rel="stylesheet" href="/assets/javascripts/pro/libs/fancybox/jquery.fancybox.css">
  
  <script type="text/javascript" src="/assets/javascripts/libs/modernizr-2.0.6.min.js"></script>
  <script type="text/javascript" src="/assets/javascripts/libs/jquery-1.6.2.min.js"></script>
  <script type="text/javascript" src="/assets/javascripts/libs/jquery-ui-1.8.16.custom.min.js"></script>
  <script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
  <script type="text/javascript" src="/ckeditor/adapters/jquery.js"></script>
<!-- bootstrap daterangepicker -->
<link rel="stylesheet" type="text/css" media="all" href="/assets/stylesheets/common/daterangepicker-bs3.css" />
<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">




</head>

<body>

    <div id="menu">
        <?php echo $this->navigation()->menu()->setPartial('menu.phtml')->render(); ?>
        <span id="logo"></span>
    </div>

    <?php echo $this->layout()->content; ?>

    <script defer type="text/javascript" src="/assets/javascripts/libs/jquery.fancybox.js"></script>

    <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
    <!-- // <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script> -->
    <!-- <script>window.jQuery || document.write('<script src="js/libs/jquery-1.6.2.min.js"><\/script>')</script> -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script type="text/javascript" src="/assets/javascripts/common/daterangepicker.js"></script>
    <script type="text/javascript" src="/assets/javascripts/common/moment.js"></script>
    <script type="text/javascript" src="/assets/library/bootstrap/js/bootstrap.min.js"></script>

    <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
    <![endif]-->
  
</body>
</html>