<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="fr"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="fr"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="fr"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="fr"> <!--<![endif]-->
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>Alterre</title>
    <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    <meta name="description" content="Alterre - le moteur de recherche du Partage">
    <meta name="author" content="Yooroxe.fr">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <?php echo $this->headTitle() ?>

    <link rel="stylesheet" href="/assets/dist/bootstrap3.0/css/bootstrap.min.css">
    <link href="/assets/dist/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/assets/dist/bootstrap-select/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="/assets/dist/bootstrap-social/bootstrap-social.css" />
    <link rel="stylesheet" href="/assets/dist/bootstrap-fileupload/bootstrap-fileupload.min.css" />
    
    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>

    <link href="/assets/css/alterre.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/home.css" rel="stylesheet" type="text/css">

    <link rel="icon" type="image/png" href="/assets/img/favicon.png" />

  </head>

  <body>
    <nav id="" class="navbar navbar-default navbar-fixed-top" role="navigation">
      <!-- <div class="container"> -->
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-main">

          <ul class="nav navbar-nav navbar-right">
           
            <?php 
            if(1==0){
              if ($this->layout()->isConnected==true) { 
                ?>
                  <li><a style="cursor:pointer;" id="loginpopup">Inscription / Connexion</a></li>
              <?php
              }else { 
                ?>
                
                <li class="dropdown user">

                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> 
                    <img alt="" class="profilPicture img-circle" src="<?php echo $this->user->getProfilPicture(); ?>">
                    <span class="username"><?php echo $this->layout()->user->firstname; ?></span>
                    <i class="fa fa-angle-down"></i>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="/logout"><i class="fa fa-power-off"></i> Déconnexion</a></li>
                  </ul>
                </li>
              <?php
              } 
            }
            ?>
            
          </ul>


        </div><!-- /.navbar-collapse -->

      <!-- </div>/.container-fluid -->
    </nav>

    <div class="content">
      <?php echo $this->layout()->content;?>
    </div>

    <footer>

      <nav class="navbar navbar-default text-center">
        <a href="#">A propos d'Alterre</a>
        <a href="#">Mentions légales</a>
        <a href="#">Contact</a>
      </nav>

    </footer>


  <!-- Code for Login / Signup Popup -->
  <!-- Modal Log in -->
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
  <div class="modal-dialog" style="margin-top: 150px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fermer</span></button>
        <h4 class="modal-title">Connexion</h4>
      </div>

      <div class="modal-body" id="login_details">
          <form id="facebookForm" role="form" action="/login" method="post">
              <div class="row text-center ">
                  <div class="col-md-12" >
                    <a class="btn btn-block btn-social btn-facebook" href='<?php echo $this->layout()->facebookAuthUrl; ?>'>
                      <i class="fa fa-facebook"></i>Se connecter avec facebook
                    </a>
                  </div>
              </div>
              <br>
              <div class="row text-center hide">
                  <div class="col-md-12" >
                       <a class="btn btn-block btn-social btn-google-plus" href='<?php echo $this->layout()->googleAuthUrl; ?>'>
                      <i class="fa fa-google-plus"></i>Se connecter avec Google+
                    </a>
                  </div>
              </div>

          </form>
          <form id="loginForm" role="form" action="/connexion" method="post">
              <div class="row loginOr "><div class="col-xs-12"><hr class="hrOr"><span class="spanOr">ou</span></div></div>

              <div class="form-group"><input required id="login_email" name="login_email" type="email" class="form-control" placeholder="Adresse email"></div>
              <div class="form-group"><input required id="login_password"  name="login_password" type="password" class="form-control" placeholder="Mot de passe"></div>
              
              <div class="row rememberMe">
                <div class="col-xs-6 col-sm-6">
                  <label>
                     <input id="remember" name="remember" type="checkbox" /> <?php echo $this->translate('Se souvenir de moi'); ?>
                  </label>
                </div>
                <div class="col-xs-6 col-sm-6">
                  <p class="omb_forgotPwd">
                    <a href="/mot-de-passe-oublie"><?php echo $this->translate('Mot de passe oublié ?');?></a>
                  </p>
                </div>
              </div>
              <input type="hidden" id="url_edition_connexion" name="url_edition_connexion" value="">
              <div class="form-group">
                  <button type="submit" class="btn btn-alterre btn-lg btn-block">CONNEXION</button>
              </div>

              <div class="text-center notMember">
                <span>Pas encore membre ?</span>
                <span id="signup-link" style="cursor:pointer;" class="text-info">Inscrivez-vous !</span>
              </div>

          </form>
      </div><!-- /.modal-body -->

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
 <!--Modal Login Ends -->


  <!-- Modal Log in -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
  <div class="modal-dialog" style="margin-top: 20px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fermer</span></button>
        <h4 class="modal-title">Inscription</h4>
      </div>
      <div class="modal-body" id="login_details">
            <form id="signupForm" role="form" action="/user/inscription" method="post">
              <div class="row text-center hide">
                  <div class="col-md-12" >
                      <button type="button" href="<?php $this->facebookAuthUrl ?>" class="btn btn-primary btn-block">S'inscrire avec Facebook</button>
                  </div>
              </div>
              <br>
              <div class="row text-center hide">
                  <div class="col-md-12" >
                      <button type="button" href="<?php $this->googleAuthUrl ?>" class="btn btn-danger btn-block">S'inscrire avec Google+</button>
                  </div>
              </div>

              <div class="row loginOr hide"><div class="col-xs-12"><hr class="hrOr"><span class="spanOr">ou</span></div></div>

              <div class="form-group controls"><input required id="lastname" name="lastname" type="text" class="form-control" placeholder="Nom"></div>
              <div class="form-group controls"><input required id="firstname" name="firstname" type="text" class="form-control" placeholder="Prénom"></div>
              <div class="form-group controls"><input required id="email" name="email" type="email" class="form-control" placeholder="Adresse Email">
              <span id="email-error" class="help-block font-red fa-05"></span>
            </div>
              <div class="form-group controls"><input required id="password" name="password" type="password" class="form-control" placeholder="Mot de passe"></div>
              <div class="form-group controls"><input required id="confirm_password" name="confirm_password"  type="password" class="form-control" placeholder="Confirmez le mot de passe"></div>
              
              <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 acceptCGU" >
                   En vous inscrivant, vous acceptez les <a href="#" data-toggle="modal" data-target="#t_and_c_m">Conditions Générales</a> , ainsi que les Cookies.
                </div>
              </div>
              <input type="hidden" id="url_edition_inscription" name="url_edition_inscription" value="">
              <div class="form-group">
                  <button type="submit" id="signupSubmit" class="btn btn-alterre btn-lg btn-block">INSCRIPTION</button>
              </div>

              <div class="text-center notMember">
                <span>Déjà membre ?</span>
                <span id="login-link" style="cursor:pointer;" class="text-info">Connectez-vous !</span>
              </div>

          </form>
      </div><!-- /.modal-body -->

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Modal -->
<div class="modal fade" id="t_and_c_m" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">Conditions générales d'utilisation</h4>
      </div>
      <div class="modal-body">
                <h3>A rédiger</h3>
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">J'ai compris</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<input type="hidden" name="lat" id="lat" /> 
<input type="hidden" name="lng" id="lng" />

    <!-- jQuery Version 1.11.0 -->
    <script src="/assets/dist/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/assets/dist/bootstrap3.0/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="/assets/dist/classie.js"></script>
    <script src="/assets/dist/modernizr-2.8.3.js"></script>

    <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
    <script src="/assets/dist/geocomplete/jquery.geocomplete.js"></script>
    <script src="/assets/dist/Google.js"></script>
    <script src="/assets/dist/bootstrap-select/js/bootstrap-select.min.js"></script>
    <script src="/assets/dist/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/assets/js/alterre.js"></script>

    <?php echo $this->headScript() ?>
    
   <script type="text/javascript">

      $(function(){
              $("#signupForm").validate({
                rules: {
                    firstname: "required",
                    lastname: "required",
                    email: "required",
                    password: {
                        required: true,
                        minlength: 5
                    },
                    confirm_password: {
                        required: true,
                        minlength: 5,
                        equalTo: "#password"
                    }
                },
                messages: {
                    // firstname: "Votre nom est obligatoire pour garantir l\'identité réelle",
                    // lastname: "Votre prénom est obligatoire pour garantir l\'identité réelle",
                    password: {
                        required: "Veuillez entrer un mot de passe",
                        minlength: "Le mot de passe doit contenir au moins 5 caractères"
                    },
                    confirm_password: {
                        required: "Veuillez ressaisir votre mot de passe",
                        minlength: "Le mot de passe doit contenir au moins 5 caractères",
                        equalTo: "Veuillez entrer le même mot de passe"
                    }
                },
                highlight: function(element) {
                $(element).closest('.form-group').addClass('has-error');
                },
                unhighlight: function(element) {
                    $(element).closest('.form-group').removeClass('has-error');
                },
                errorElement: 'span',
                errorClass: 'help-block',
                errorPlacement: function(error, element) {
                    if(element.parent('.input-group').length) {
                        error.insertAfter(element.parent());
                    } else {
                        error.insertAfter(element);
                    }
                }
            });

            $("#loginForm").validate({
                rules: {
                    login_email: "required",
                    login_password: {
                        required: true,
                        minlength: 5
                    }
                },
                messages: {
                    login_email: {
                        required: "Veuillez entrer votre email"
                    },
                    login_password: {
                        required: "Veuillez entrer votre mot de passe",
                        minlength: "Le mot de passe doit contenir au moins 5 caractères"
                    }
                },
                highlight: function(element) {
                $(element).closest('.form-group').addClass('has-error');
                },
                unhighlight: function(element) {
                    $(element).closest('.form-group').removeClass('has-error');
                },
                errorElement: 'span',
                errorClass: 'help-block',
                errorPlacement: function(error, element) {
                    if(element.parent('.input-group').length) {
                        error.insertAfter(element.parent());
                    } else {
                        error.insertAfter(element);
                    }
                }
            });

      

            $('#email').on('blur', function() {
                
                $.ajax({
                    url: "/user/verifemail",
                    dataType: "json",
                    data: {
                        email: $('#email').val()
                    },
                    success: function(data) {
                        // response(data);
                        console.log(data);
                        if(data != false){
                          console.log("ok");
                            $("#email").addClass('font-red');
                            $("#email-error").addClass('font-red');
                            $("#email-error").text("Cet email est déjà utilisé, veuillez le changer");
                            $("#signupSubmit").addClass('disabled');
                        }else{
                            $("#email").removeClass('font-red');
                            $("#email-error").addClass('font-citeez');
                            $("#signupSubmit").removeClass('disabled');
                            $("#email-error").hide(); 
                        }
                    }
                });
            });

          });

    </script>
        <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-61190020-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>





