
<div class="ariane">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="/">Accueil</a></li>
            <?php if(isset($this->orga->domain)){ ?>
                <li><a href="/<?php echo $this->orga->domain; ?>/actions"><?php echo $this->orga->domain; ?></a></li>
                <li><a href="/<?php echo $this->orga->domain; ?>/actions">Annonces</a></li>
            <?php }else{?>
                <li><a href="<?php echo $this->url(array("controller" => "actions", "action" => "index"), "", true); ?>">annonces</a></li>
            <?php }?>

            <li class="active"> <?php echo $this->project->name; ?></li>
        </ol>
    </div>
</div>

<div class="details-project">

    <div class="container">

        <div class="section-header">
            <h2 class="section-heading"><?php echo $this->project->name; ?></h2>
            <h6>by <b><?php echo $this->project->User->firstname." ".$this->project->User->lastname; ?></b></h6>
        </div>
        
        <div class="row">
            <div class="col-lg-7 col-md-7 MR20">
                <div class="row">
                    <!-- <div class="responsive-video"> -->
                        <!-- <iframe  src="//www.youtube.com/embed/ZIjPpCpfNzY" frameborder="0" allowfullscreen></iframe> -->
                    <!-- </div> -->
                    <?php if($this->project->CzMedia->id!="0"){ ?>
                    <img class="img-responsive" src="<?php echo $this->project->CzMedia->getThumb(800,600); ?>" alt="<?php echo htmlentities($this->project->name); ?>">
                    <?php } ?>
                </div>
                <div class="row">
                    <i class="fa fa-map-marker"></i> <?php echo $this->project->CzAddress->zipcode." ".$this->project->CzAddress->city.", ".$this->project->CzAddress->country_name; ?>
                    <i class="fa fa-tag PL30"></i></i> <?php echo $this->project->CzCategory->name; ?>
                </div>
                <div class="row">
                    <h3>Description de l'annonce</h3>
                    <?php echo $this->project->description; ?>
                </div>
            </div>
            <div class="col-lg-5 col-md-5">
                <div class="row">
                    <a href="#helpProject" role="button" data-toggle="modal" class="btn btn-danger btn-lg btn-block">Répondre à cette annonce</a>
                </div>
                <div class="fb-like" data-href="<?php echo $_SERVER['REQUEST_URI'];?>" data-layout="button_count" data-action="recommend" data-show-faces="true" data-share="false"></div>
                <hr>
                <div class="row">
                    <div class="col-lg-9 col-md-9">
                        <p class="fa-1"><b><?php echo $this->project->User->firstname." ".$this->project->User->lastname; ?></b></p>
                        <!-- <p><i class="fa fa-heart"></i> 00 coups de coeur</p> -->
                       
                    </div>
                    <div class="col-lg-3 col-md-3">
                        <img class="" alt="" src="<?php echo $this->project->User->CzMedia->getThumb(30,30); ?>">
                    </div>
                </div>
                <hr>
            </div>
        </div>

        <input type="hidden" id="address_addressLiteral" name="address_addressLiteral">
        <input type="hidden" id="address_zipcode" name="address_zipcode">
        <input type="hidden" id="address_city" name="address_city">
        <input type="hidden" id="address_department" name="address_department">
        <input type="hidden" id="address_departmentName" name="address_departmentName">
        <input type="hidden" id="address_regionName" name="address_regionName">
        <input type="hidden" id="address_country" name="address_country">
        <input type="hidden" id="address_countryCode" name="address_countryCode">
        <input type="hidden" id="address_lat" name="address_lat">
        <input type="hidden" id="address_lng" name="address_lng">



    <div id="helpProject" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                   <b><?php echo $this->translate("Comment souhaitez-vous aider ce projet ?");?></b>
                </div>
                <?php if(isset($_SESSION["troovon"]["user"])){ ?>
                <div class="modal-body">
                    <textarea autofocus="" style="width: 100%;height:200px;"></textarea>
                    <p>
                    <b><u>Projet :</u></b> <?php echo $this->project->name; ?><br> 
                    Besoin humain : <span class="font-cz"><?php echo $this->project->humanNeed; ?></span><br>
                    Besoin matériel : <span class="font-cz"><?php echo $this->project->materialNeed; ?></span><br>
                    Besoin financier : <span class="font-cz"><?php echo $this->project->financialNeed; ?></span></p>
                </div>
                <?php }?>
                <div class="modal-footer">
                    <?php if(isset($_SESSION["troovon"]["user"])){ ?>
                    <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Cancel')?></button>
                    <button id="helpProjectSubmit" class="btn btn-danger btn-lg" data-id="<?php echo $this->project->id?>"><?php echo $this->translate('Envoyer mon aide')?></button>
                    <?php }else{ ?>
                    <span class="font-red"><i>Vous devez être connecté pour contacter le porteur de projet.</i></span>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>


    <div id="messageModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <?php echo $this->translate('A :')?>
                    <span class="label label-info">
                        <?php echo $this->project->User->firstname." ".$this->project->User->lastname; ?>
                    </span>
                </div>
                <?php if(isset($_SESSION["troovon"]["user"])){ ?>
                    <div class="modal-body">
                       <label><?php echo $this->translate("Message");?></label>
                        <textarea autofocus="" style="width: 100%;height:200px;"></textarea>
                        <label for="copy" class="checkbox">
                            <input type="checkbox" name="copy" class="copy" id="copy" /> <?php echo $this->translate('Recevoir une copie') ?>
                        </label>
                    </div>
                <?php } ?>
                <div class="modal-footer">
                    <?php if(isset($_SESSION["troovon"]["user"])){ ?>
                    <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Cancel')?></button>
                    <button id="contactSubmit" class="btn btn-danger btn-lg" data-id="<?php echo $this->project->User->id?>" data-project="<?php echo $this->project->id?>"><?php echo $this->translate('Envoyer')?></button>
                    <?php }else{ ?>
                    <span class="font-red"><i>Vous devez être connecté pour contacter le porteur de projet.</i></span>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
    </div>


<?php $this->headScript()->captureStart(); ?>
<?php if(false): ?><script><?php endif; ?>
$(document).ready(function() {


        $("#helpProjectSubmit").click(function(e){
            // alert("eeeeee");
            e.preventDefault();

            var datas=$('#helpProject textarea').val();
            var projectId =$(e.currentTarget).data('id');
            //Fermeture de la modal
            $('#helpProject').modal('hide')

            $.ajax({
                url: "/projets/aiderceprojet",
                dataType: "json",
                type: "POST",
                data: {
                    msg: datas,
                    id:projectId
                },
                success: function(data) {
                    console.log(data);
                    // if(data[succes] == 'ok'){
                    //     $("#div-infoville").hide();
                    // }else{
                    //     $("#div-infoville").text("La ville de "+city.toUpperCase()+" n'est pas encore ouverte sur Citeez, VOTEZ pour que "+city.toUpperCase()+" remonte dans la liste d'attente !");
                    // }
                }
            });
        });

        $("#contactSubmit").click(function(e){
            // alert("eeeeee");
            e.preventDefault();

            var datas=$('#messageModal textarea').val();
            var userId =$(e.currentTarget).data('id');
            var projectId =$(e.currentTarget).data('project');
            //Fermeture de la modal
            $('#messageModal').modal('hide')

            $.ajax({
                url: "/user/write",
                dataType: "json",
                type: "POST",
                data: {
                    msg: datas,
                    userId:userId,
                    projectId:projectId
                },
                success: function(data) {
                    console.log(data);
                    // if(data[succes] == 'ok'){
                    //     $("#div-infoville").hide();
                    // }else{
                    //     $("#div-infoville").text("La ville de "+city.toUpperCase()+" n'est pas encore ouverte sur Citeez, VOTEZ pour que "+city.toUpperCase()+" remonte dans la liste d'attente !");
                    // }
                }
            });
        });

});
<?php if(false): ?></script><?php endif; ?>
<?php $this->headScript()->captureEnd(); ?>



