<div class="modal fade delete-one" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('Suppression') ?></h4>
      </div>
      <div class="modal-body">
        <?php echo $this->text?> <strong><span class="delete-value"></span></strong>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default"><a class="delete-link" href="#"><?php echo $this->translate('Turn off the company and the users') ?></a></button>
        <button type="button" class="btn btn-default"><a class="delete-link-light" href="#"><?php echo $this->translate('Turn off the company') ?></a></button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

    $(document).ready(function() {

        var action = '<?php echo $this->action?>';
        var paramName = '<?php echo $this->paramName?>';

        $('.delete').click(function(){
            $('span.delete-value').html($(this).data('value'));
            $('a.delete-link').attr('href',action+'/'+paramName+'/'+$(this).data(paramName)+'?delusers=false&controllerR='+'<?php echo $this->controllerRetour ?>'+'&actionR='+'<?php echo $this->actionRetour ?>');
            $('a.delete-link-light').attr('href',action+'/'+paramName+'/'+$(this).data(paramName)+'?delusers=true&controllerR='+'<?php echo $this->controllerRetour ?>'+'&actionR='+'<?php echo $this->actionRetour ?>');
        });
    });

</script>