<?php if (count($this->pagesInRange) > 1) { ?>
<div class="paginate wrapper">

	<ul class="pagination">
	
	    <!-- Previous page link -->
	    <?php if (isset($this->previous)): 
	        $params = array('page' => $this->previous);
	    ?>
	    	<li class="prev"><a href="?p=<?php  echo $this->previous; ?>"><strong>&lsaquo;</strong></a></li>
	    <?php endif; ?>
	    
	    <!-- Numbered page links -->
	    <?php foreach ($this->pagesInRange as $page) {

	    ?>
	        <?php if ($page != $this->current) {?>
            <li><a href="?p=<?php echo $page; ?>"><?php echo $page; ?></a></li>
	        <?php } else { ?>
	            <li class="current"><a href=""><?php echo $page; ?></a></li>
	        <?php } ?>
	    <?php } ?>
	    
	    <!-- Next page link -->
	    <?php if (isset($this->next)): 
	        $params = array('page' => $this->next);
	    ?>
	    	<li class="next"><a href="?p=<?php echo $this->next; ?>"><strong>&rsaquo;</strong></a></li>
	    <?php endif; ?>

        <li class="clear"></li>
	 </ul>
 </div>
<?php } ?>