<div id="submenu">
<ul>    
        <li>
            <a href="/index" class="arrow"><?php echo $this->translate('General creations') ?></a>
        </li> 
        <li>
            <a href="/index/newcompanies" class="arrow"><?php echo $this->translate('New companies') ?></a>
        </li>
        <li>
            <a href="/index/newads" class="arrow"><?php echo $this->translate('new ads') ?></a>
        </li>
        <li>
            <a href="/index/newusers" class="arrow"><?php echo $this->translate('New users') ?></a>
        </li>
    </ul>
</div>

