<div id="submenu">

    <ul>
        <li>
            <a href="/modules" class="arrow"><?php echo $this->translate('Carpool') ?></a>
        </li>
        <li>
            <a href="/modules" class="arrow"><?php echo $this->translate('Music') ?></a>
        </li>
        <li>
            <a href="/modules" class="arrow"><?php echo $this->translate('Works council offers ') ?></a>
        </li>
    </ul>
</div>