<div id="submenu">
    <ul>
        <li>
            <a href="/parameters/universes" class="arrow"><?php echo $this->translate('Universes') ?></a>
        </li>
        <li>
            <a href="/parameters/privileges" class="arrow"><?php echo $this->translate('Benefits') ?></a>
        </li>
        <li>
            <a href="/parameters/default-field" class="arrow"><?php echo $this->translate('Default fields') ?></a>
        </li>
        <li>
            <a href="/parameters/currencies" class="arrow"><?php echo $this->translate('Currencies') ?></a>
        </li>
        <li>
            <a href="/parameters/countries" class="arrow"><?php echo $this->translate('Countries') ?></a>
        </li>
        <li>
            <a href="/parameters/languages" class="arrow"><?php echo $this->translate('Languages ​​and Translations') ?></a>
        </li>
    </ul>
</div>