<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_CzCategory', 'doctrine');

/**
 * Model_Entity_CzCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $parent
 * @property enum $type
 * @property enum $state
 * @property integer $picto
 * @property integer $image
 * @property integer $orga_id
 * @property integer $position
 * @property Doctrine_Collection $CzCategory
 * @property Model_CzMedia $CzMedia
 * @property Model_CzMedia $CzMedia_3
 * @property Doctrine_Collection $CzProject
 * @property Doctrine_Collection $CzProjectCategory
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Entity_CzCategory extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('cz_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('parent', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('type', 'enum', 7, array(
             'type' => 'enum',
             'length' => 7,
             'fixed' => false,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'projet',
              1 => 'annonce',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('state', 'enum', 7, array(
             'type' => 'enum',
             'length' => 7,
             'fixed' => false,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'enable',
              1 => 'disable',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('picto', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('image', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('orga_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_CzCategory as CzCategory', array(
             'local' => 'id',
             'foreign' => 'parent'));

        $this->hasOne('Model_CzMedia as CzMedia', array(
             'local' => 'picto',
             'foreign' => 'id'));

        $this->hasOne('Model_CzMedia as CzMedia_3', array(
             'local' => 'image',
             'foreign' => 'id'));

        $this->hasMany('Model_CzProject as CzProject', array(
             'local' => 'id',
             'foreign' => 'category'));

        $this->hasMany('Model_CzProjectCategory as CzProjectCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}