<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_CzProjectCategory', 'doctrine');

/**
 * Model_Entity_CzProjectCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $category_id
 * @property enum $state
 * @property Model_CzCategory $CzCategory
 * @property Model_CzProject $CzProject
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Entity_CzProjectCategory extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('cz_project_category');
        $this->hasColumn('project_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('state', 'enum', 7, array(
             'type' => 'enum',
             'length' => 7,
             'fixed' => false,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'enable',
              1 => 'disable',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_CzCategory as CzCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('Model_CzProject as CzProject', array(
             'local' => 'project_id',
             'foreign' => 'id'));
    }
}