<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_CzProjectMaterialneed', 'doctrine');

/**
 * Model_Entity_CzProjectMaterialneed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $materialneed_id
 * @property timestamp $date
 * @property Model_CzProject $CzProject
 * @property Model_CzMaterialneed $CzMaterialneed
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Entity_CzProjectMaterialneed extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('cz_project_materialneed');
        $this->hasColumn('project_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('materialneed_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_CzProject as CzProject', array(
             'local' => 'project_id',
             'foreign' => 'id'));

        $this->hasOne('Model_CzMaterialneed as CzMaterialneed', array(
             'local' => 'materialneed_id',
             'foreign' => 'id'));
    }
}