<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Universe', 'doctrine');

/**
 * Model_Entity_Universe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $position
 * @property Doctrine_Collection $Category
 * @property Doctrine_Collection $TranslateUniverse
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Entity_Universe extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('universe');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_Category as Category', array(
             'local' => 'id',
             'foreign' => 'universe_id'));

        $this->hasMany('Model_TranslateUniverse as TranslateUniverse', array(
             'local' => 'id',
             'foreign' => 'universe_id'));
    }
}