             <section class="masthead">
             	<div id="carousel-example" class="carousel slide" data-ride="carousel">

                    <div class="carousel-inner">
                        <div class="item active">

                            <img src="/assets/img/home/5.jpg" alt="" class="opacity60"/>
                            <div class="carousel-caption" >
                                <!-- <h4 class="back-light">Aenean faucibus luctus enim. Duis quis sem risu suspend lacinia elementum nunc.</h4> -->
                            </div>
                        </div>
                    </div>
                </div>

<!-- 		        <video class="masthead-video" autoplay loop muted>
		          <source src="/assets/dist/covervid/videos/dreamscapes.mp4" type="video/mp4">
		          <source src="/assets/dist/covervid/videos/dreamscapes.webm" type="video/webm">
		        </video> -->
			    <div class="masthead-overlay"></div>
			    <h1>Création d'un jardin partagé<span>Nantes - 256 votes  - 5847 vues - 365 partages</span></h1>
			    <p><a class="btn btn-primary btn-lg" href="#" role="button">Découvrir le projet</a></p>


			  </section>


			  	<div class="jumbotron">
					  <h1>Hello, world!</h1>
					  <p>...</p>
					  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
				</div>




				<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
				  <!-- Indicators -->
				  <ol class="carousel-indicators">
				    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
				    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
				  </ol>

				  <!-- Wrapper for slides -->
				  <div class="carousel-inner" role="listbox">
				    <div class="item active">
				      <img src="http://cssdeck.com/uploads/media/items/8/8kEc1hS.png" alt="..." style="height:200px;">
				      <div class="carousel-caption">
				        ...
				      </div>
				    </div>
				    <div class="item">
				      <img src="http://cssdeck.com/uploads/media/items/6/6f3nXse.png" alt="..." style="height:200px;">
				      <div class="carousel-caption">
				        ...
				      </div>
				    </div>
				    <div class="item">
				      <img src="http://cssdeck.com/uploads/media/items/1/1swi3Qy.png" alt="..." style="height:200px;">
				      <div class="carousel-caption">
				        ...
				      </div>
				    </div>
				  </div>

				  <!-- Controls -->
				  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>

<div id="wrapper">
	<div id="columns">

		<div class="pin">
			<img src="http://cssdeck.com/uploads/media/items/1/1swi3Qy.png" />
			<p>
				Donec a fermentum nisi. 
			</p>
		</div>
	
		<div class="pin">
			<img src="http://cssdeck.com/uploads/media/items/6/6f3nXse.png" />
			<p>
				Nullam eget lectus augue. Donec eu sem sit amet ligula 
				faucibus suscipit. Suspendisse rutrum turpis quis nunc 
				convallis quis aliquam mauris suscipit.
			</p>
		</div>
	
		<div class="pin">
			<img src="http://cssdeck.com/uploads/media/items/8/8kEc1hS.png" />
			<p>
				Nullam eget lectus augue. Donec eu sem sit amet ligula 
				faucibus suscipit. Suspendisse rutrum turpis quis nunc 
				convallis quis aliquam mauris suscipit.
			</p>
		</div>
	
		<div class="pin">
			<img src="http://cssdeck.com/uploads/media/items/1/1swi3Qy.png" />
			<p>
				Donec a fermentum nisi. Integer dolor est, commodo ut 
				sagittis vitae, egestas at augue. 
			</p>
		</div>
	</div>
</div>
