<!--        <!-- <section id="home" class="text-center"> -->
           
             <section class="masthead">
		        <video class="masthead-video" autoplay loop muted>
		          <source src="/assets/dist/covervid/videos/dreamscapes.mp4" type="video/mp4">
		          <source src="/assets/dist/covervid/videos/dreamscapes.webm" type="video/webm">
		        </video>
			    <div class="masthead-overlay"></div>
			    <h1>Etes-vous prêt ?<span>Devenez acteur de votre ville, maintenant !</span></h1>


			  </section>
  
       <!-- </section> -->
    <!--/.SLIDESHOW END-->


    <!-- Features Section -->
    <section class="features" id="features">
        <div class="container">
                
                <!-- SECTION HEADER -->
            <div class="section-header">
                
                <!-- SECTION TITLE -->
                <h2 class="section-heading"><?php echo $this->translate('Titre percutaNT'); ?></h2>
                
                <!-- SHORT DESCRIPTION ABOUT THE SECTION -->
                <h6>
                    <?php echo $this->translate('Une phrase percutante explicant le concept'); ?>
                </h6>
            </div>
            <!-- / END SECTION HEADER -->
            
            <!-- FEATURS -->
            <div class="row">
            
                <!-- FEATURES COLUMN LEFT -->
                <div class="col-md-6 col-sm-6">
                    
                    <div class="col-md-12 col-sm-12 centered">
                        <h3 class="blue-ft"><?php echo $this->translate('Pour les utilisateurs'); ?></h3><br>
                    </div>

                    <div class="feature">
                        <div class="feature-icon">
                             <span class="fa-stack">
                                <i class="fa fa-cab fa-stack-1x "></i>
                            </span>
                        </div>
                        <h5>Ajout, consultation de petites annonces</h5>
                        <p>
                             Echangez, partagez, donnez, vendez, achetez, louez…<br>Tout est possible !
                        </p>
                    </div>

                    <div class="feature">
                        <div class="feature-icon">
                             <span class="fa-stack">
                                <i class="fa fa-users fa-stack-1x "></i>
                            </span>
                        </div>
                        <h5>Interconnexion des membres</h5>
                        <p>
                            Covoiturez avec le salarié de la société d’en face !<br>
                        </p>
                    </div>
                    <div class="feature">
                        <div class="feature-icon">
                             <span class="fa-stack">
                                <i class="fa fa-ticket fa-stack-1x "></i>
                            </span>
                        </div>
                        <h5>Offres partenaires</h5>
                        <p>
                            Profitez de tarifs réduits exclusifs à Troovon.
                        </p>
                    </div>
                    <div class="feature">
                        <div class="feature-icon">
                             <span class="fa-stack">
                                <i class="fa fa-check-square-o fa-stack-1x "></i>
                            </span>
                        </div>
                        <h5>Certification de profil</h5>
                        <p>
                          Gagnez en crédibilité pour optimiser vos échanges.
                        </p>
                    </div>

                </div> <!-- / FEATURES COLUMN LEFT -->
                
                <!-- FEATURES COLUMN RIGHT -->
                <div class="col-md-6 col-sm-6">
                    <div class="col-md-12 col-sm-12 centered">
                        <h3 class="blue-ft"><?php echo $this->translate('Pour les gestionnaires'); ?></h3><br>
                    </div>
                    <div class="feature">
                        <div class="feature-icon">
                             <span class="fa-stack">
                                <i class="fa fa-newspaper-o fa-stack-1x "></i>
                            </span>
                        </div>
                        <h5>Création d’une page d’accueil à l'image de votre CE</h5>
                        <p>
                             Renseignez les horaires de permanence, les coordonnées et les interlocuteurs du CE.
                        </p>
                    </div>
                    
                    <div class="feature">
                        <div class="feature-icon">
                             <span class="fa-stack">
                                <i class="fa fa-sliders fa-stack-1x "></i>
                            </span>
                        </div>
                        <h5>Paramétrage des fonctionnalités collaboratives</h5>
                        <p>
                             Covoiturage, babysitting, partage de potagers, partage de compétences… faites votre choix parmi près de 15 catégories.
                        </p>
                    </div>

                    <div class="feature">
                        <div class="feature-icon">
                             <span class="fa-stack">
                                <i class="fa fa-gift fa-stack-1x "></i>
                            </span>
                        </div>
                        <h5>Diffusion des offres et informations du CE</h5>
                        <p>
                             Partagez rapidement et simplement votre catalogue d’offres CE.
                        </p>
                    </div>

                    <div class="feature">
                        <div class="feature-icon">
                             <span class="fa-stack">
                                <i class="fa fa-bullhorn fa-stack-1x "></i>
                            </span>
                        </div>
                        <h5>Information des salariés en temps réel</h5>
                        <p>
                             Une offre de dernière minute, une information urgente... Troovon vous permet de l’envoyer en un clic.
                        </p>
                    </div>
                    
                </div> <!-- / END FEATURES COLUMN RIGHT -->
            </div> <!-- / END FEATURES -->
        </div> <!-- / END CONTAINER -->
    </section>


    <!--/.INTRO END-->
      <section id="offer"  >
           <div class="container">
           <div class="row   alert alert-info" >
                 <div class="col-md-8 col-sm-8">
                      <h1>  Download Deatils Now For Latest Offers</h1>
                 </div>
                 <div class="col-md-4 col-sm-4" style="padding-top: 15px;">
                     <a href="#" class=" btn btn-primary btn-lg">GRAB IT HERE NOW</a> 
                 </div>
                          
               </div>
               </div>
      </section>
      <!--/.OFFFER END-->
         <section id="just-intro">
             <div class="container">
             <div class="row text-center pad-row">
            <div class="col-md-4  col-sm-4">
                 <i class="fa fa-desktop fa-5x"></i>
                            <h4> <strong>Sure Quique Menu</strong> </h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                       <a href="#" class="btn btn-primary" >Read Details</a>    
                </div>
             <div class="col-md-4  col-sm-4">
                 <i class="fa fa-flask  fa-5x"></i>
                            <h4> <strong>Sure Quique Menu</strong> </h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                           <a href="#" class="btn btn-primary" >Read Details</a>
                </div>
            <div class="col-md-4  col-sm-4">
                  <i class="fa fa-pencil  fa-5x"></i>
                            <h4> <strong>Sure Quique Menu</strong> </h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                       <a href="#" class="btn btn-primary" >Read Details</a>    
                </div>
                    
            </div>
                 </div>
         </section>
     <!--/.JUST-INTRO END-->
     <section  class="note-sec" >
         
               <div class="container">
           <div class="row text-center pad-row" >
            <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 ">
                <i class="fa fa-quote-left fa-3x"></i>
               <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                     Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                            </p>
                </div>
               </div>
            </div>   
           
       </section>
    <!--/.NOTE END-->
     <section id="clients"  >
        
                
            <div class="container">
           <div class="row text-center pad-bottom" >
            <div class="col-md-12">
                <img src="/assets/img/home/clients.png" alt="" class="img-responsive" />
            </div>
               
               </div>
        </div>
        </section>
     <!--/.CLIENTS END-->
    <section id="footer-sec" >
             
            <div class="container">
           <div class="row  pad-bottom" >
            <div class="col-md-4">
                <h4> <strong>ABOUT COMPANY</strong> </h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                <a href="#" >read more</a>
                </div>
               <div class="col-md-4">
                    <h4> <strong>SOCIAL LINKS</strong> </h4>
                   <p>
                     <a href="#"><i class="fa fa-facebook-square fa-3x"  ></i></a>  
                        <a href="#"><i class="fa fa-twitter-square fa-3x"  ></i></a>  
                        <a href="#"><i class="fa fa-linkedin-square fa-3x"  ></i></a>  
                       <a href="#"><i class="fa fa-google-plus-square fa-3x"  ></i></a>  
                   </p>
                </div>
               <div class="col-md-4">
                   <h4> <strong>OUR LOCATION</strong> </h4>
                            <p>
                               234/JK , The Wondre Land, <br />
                               Newyork Street Junction  <br />
                               JUST USA -10909094
                            </p>
                    <a href="#" class="btn btn-primary" >SEND QUERY</a>
                </div>
               </div>
            </div>
    </section>         
 -->