<div class="container PT50">

	<div class="row" >
        <div class="col-md-6">
        	<img src="/assets/img/collectivites/coeur.jpg" class="img-responsive">
        </div>
         
        <div class="col-md-6">
        	<h2><span class="fa-stack fa-lg"><i class="fa fa-bullhorn fa-stack-1x"></i></span>J'alerte</h2>
           <p>Tu constates régulièrement un éclairage défaillant dans ta rue ? Parfois, un dépôt sauvage d’ordures ? Un nid de poule est en train de se former dans une rue proche de chez toi ?<br><br>
           	Tu peux aider ta ville en signalant rapidement et simplement ces dysfonctionnements.<br><br>
           	Tu peux aussi profiter de cette révolution en téléchargeant dès maintenant l’application de notre partenaire : Fixmaville (<a target="_blank" href="http://www.fixmaville.fr">www.fixmaville.fr</a>)<br><br>
           	Grâce à toi, ta ville agit mieux et plus vite !</p>
          </div>
        </div>
    </div> 