<div class="container PT50">

	<div class="row" >
        <div class="col-md-6">
        	<img src="/assets/img/collectivites/coeur.jpg" class="img-responsive">
        </div>
         
        <div class="col-md-6">
        	<h2><span class="fa-stack fa-lg"><i class="fa fa-university fa-stack-1x"></i></span>Je débats </h2>
           <p>Les élus aussi ont besoin et ont la volonté d’échanger toujours plus avec leurs administrés.<br>
           	Cette page est faite pour vous afin d’interagir avec vos élus.<br><br>
           	Tu peux également soumettre une idée de débats/discussions que tu souhaites engager avec tes élus : (Titre, description rapide, description longue, localisation rapide) (Type espace Forum)<br><br>
           	Nous ferons en sorte d’entrer en relation avec ta mairie pour l’informer de ton initiative/discussion.<br><br>
           	Si tu as les coordonnées d’une personne à contacter, c’est par ici : <a target="_blank" href="mailto:contact@citeez.fr">contact@citeez.fr</a><br><br>
           	Bienvenue dans un monde de démocratie positive !</p>
          </div>
        </div>
    </div> 