<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//FR" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
	<title>Troovon vous informe !</title>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
</head>
<body>
    <table cellspacing="0" cellpadding="0" border="0" width="100%" background="http://dev.troovon.com/assets/emailing/paper.jpg"> 
		<tbody>
			<tr> 
				<td style="padding:20px 20px 40px"> 
					<table cellspacing="0" cellpadding="0" border="0" align="center" width="700">
						<tr> 
							<td align="center" style="padding:10px 0 15px"> 
								<a href="http://www.troovon.com" target="_blank" title="troovon.com" style="border:none" target="_blank"> <img src="http://dev.troovon.com/assets/emailing/troovon_logo.gif" width="143" height="60" style="vertical-align:top;outline:none;border:none" alt="Troovon vous informe"></a>
							</td> 
						</tr>
						<tr>
							<td style="padding:10px 0 10px"><img src="http://dev.troovon.com/assets/emailing/line.gif" alt="" height="2"   border="0" width="100%"/>
							</td>
						</tr>
					</table>

					<table cellspacing="0" cellpadding="0" border="0" align="center" width="700">
						<tr> 
							<td height="40" valign="top">
								<font style="font-size: 16px; line-height: 20px;" color="#666666" face="Arial" size="3">Bienvenue sur Troovon</font>
							</td> 
							<td rowspan="2"><img src="http://dev.troovon.com/assets/emailing/troovon_corpo.gif" width="97" height="97" style="vertical-align:top;outline:none;border:none" alt="Troovon"></td> 
						</tr>
						<tr> 
							<td height="40" valign="top">
								<font style="font-size: 12px; line-height: 16px;" color="#666666" face="Arial" size="3">Vous trouverez dans ce mail le récapitulatif de votre inscription.<br>Vous pouvez désormais vous connnecter sur www.troovon.com pour utiliser votre plateforme de petites annonces réservée à vos collaborateurs.</font>
							</td>
						</tr>
						<tr>
							<td colspan="2" style="padding:10px 0 10px"><img src="http://dev.troovon.com/assets/emailing/line.gif" alt="" height="2"   border="0" width="100%"/>
							</td>
						</tr>
						
					</table>

					<table cellspacing="0" cellpadding="0" border="0" align="center" width="700">
						<tr> 
							<td colspan="3" height="40" valign="top">
								<font style="font-size: 16px; line-height: 20px;" color="#666666" face="Arial" size="3">Rappel de vos identifiants</font>
							</td> 
						</tr>
						<tr> 
							<td height="100" valign="top" width="100">
								<img src="http://dev.troovon.com/assets/emailing/lock.gif" width="60" height="60" style="vertical-align:top;outline:none;border:none" alt="Troovon">
							</td> 

							<td height="100" valign="top" width="200">
								<font style="font-size: 12px; line-height: 16px;" color="#666666" face="Arial" size="3">Site :<br>Login :<br>Mot de passe :</font>
							</td>
							<td height="100" valign="top">
								<font style="font-size: 12px; line-height: 16px;" color="#666666" face="Arial" size="3"><a href="http://www.troovon.com" alt="Accédez à Troovon" title="Accédez à Troovon" target="_blank">www.troovon.com</a><br>NOM@MAIL.COM<br>******</font>
							</td>
						</tr>
						<tr> 
							<td colspan="3" height="40" valign="top">
								<font style="font-size: 12px; line-height: 20px;" color="#666666" face="Arial" size="3">Note : 	Votre mot de passe est sécurisé. En cas d'oublie, vous pouvez le réinitialiser <a href="http://www.troovon.com/user/reset-pwd" alt="Réinitialiser mon mot de passe" title="Réinitialiser mon mot de passe" target="_blank">ici</a></font>
							</td> 
						</tr>
						<tr>
							<td colspan="3" style="padding:10px 0 10px"><img src="http://dev.troovon.com/assets/emailing/line.gif" alt="" height="2"   border="0" width="100%"/>
							</td>
						</tr>
					</table>
					<table cellspacing="0" cellpadding="0" border="0" align="center" width="700">
						<tr> 
							<td height="40" valign="top">
								<font style="font-size: 16px; line-height: 20px;" color="#666666" face="Arial" size="3">Prochaine étape ?</font>
							</td>
						</tr>
						<tr>	
							<td valign="top">
								<font style="font-size: 12px; line-height: 20px;" color="#666666" face="Arial" size="3">En tant qu’administrateur, vous pouvez :
										<ul>	
											<li style="font-weight:normal; list-style-type:decimal">Renseigner les informations de votre société (adresse, Logo, etc...)</li>
											<li style="font-weight:normal; list-style-type:decimal">Ajouter des utilisateurs à votre organisation</li>
											<li style="font-weight:normal; list-style-type:decimal">Déposer les premières annonces du Comité d’Entreprise (ou déléguer ce rôle à un utilisateur).</li>
										</ul>
										En tant qu’utilisateur, vous pouvez :
										<ul>
											<li style="font-weight:normal; list-style-type:decimal">Renseigner vos informations personnelles (numéro de téléphone pour vous joindre, etc.)</li>
											<li style="font-weight:normal; list-style-type:decimal">Préparer vos annonces en brouillon et les publier quand vous le choisirez.</li>
											<li style="font-weight:normal; list-style-type:decimal">Rechercher des annonces et contacter d’autres vendeurs.</li>
										</ul>
									</font>
							</td> 
						</tr>
						<tr> 
							<td height="80" valign="center">
								<font style="font-size: 16px; line-height: 20px;" color="#666666" face="Arial" size="3">Troovon vous souhaite une excellente recherche !</font>
							</td>
						</tr>
						<tr>
							<td height="40" valign="top">
								<font style="font-size: 12px; line-height: 20px;" color="#666666" face="Arial" size="3">-- Matthieu et l'équipe Troovon --</font>
							</td>
						</tr>
						<tr>
							<td width="100%" height="40" background="http://dev.troovon.com/assets/emailing/bottom_line.gif" align="center"></td>
						</tr>
					</table>
					<table cellspacing="0" cellpadding="0" border="0" align="center" width="700">
						<tr> 
							<td height="40" align="right">
								<font style="font-size: 12px; line-height: 20px;" color="#666666" face="Arial" size="3">Aidez-nous</font>
							</td>
							<td height="40" valign="center" width="100">
								<a href="https://www.facebook.com/troovon" title="Suivez Troovon sur Facebook" style="border:none" target="_blank"> <img src="http://dev.troovon.com/assets/emailing/facebook.gif" width="40" height="40" style="vertical-align:top;outline:none;border:none" alt="Suivez Troovon sur Facebook"></a> 
							</td> 
							<td height="40" align="right" width="100">
								<font style="font-size: 12px; line-height: 20px;" color="#666666" face="Arial" size="3">Suivez-nous</font>
							</td>
							<td height="40" align="left" width="100">
								<a href="http://www.twitter.com" title="Suivez Troovon sur Twitter" style="border:none" target="_blank"> <img src="http://dev.troovon.com/assets/emailing/twitter.gif" width="40" height="40" style="vertical-align:top;outline:none;border:none" alt="Suivez Troovon sur Twitter"></a> 
							</td>
							<td height="40" align="left" width="250" >
								<img src="http://dev.troovon.com/assets/emailing/classified_ads.gif" width="160" height="40" style="vertical-align:top;outline:none;border:none" alt="Suivez Troovon sur Twitter">
							</td>
						</tr>
						<tr>
							<td style="padding:0px 0px 50px 0px"></td>
						</tr>
					</table>	
				</td>
			</tr>
		</tbody>
	</table>


	</body>
</html>