    <div class="container">
      <div class="row">

        <div class="confirmPage">

          <div class="row">
            <div class="col-lg-12 text-center">
              <h2 class=""><?php echo $this->translate('Un email a été envoyé !'); ?></h2>
              <h3 class=" text-muted"><?php echo $this->translate('Veuillez vérifier vos emails pour modifier votre mot de passe.'); ?></h3>
              <p><?php echo $this->translate('Vous n\'avez pas reçu d\'email? Regardez dans vos spams ou '); ?><a href="mailto:contact@citeez.fr" target="_blank" ><?php echo $this->translate('Contactez-nous'); ?></a></p>
            </div>
          </div>
          
        </div>
      </div>
    </div>


