<div class="ariane">
    <div class="container">
    <ol class="breadcrumb">
        <li><a href="/">Accueil</a></li>
        <li class="active">Réinitialisation du mot de passe</li>
    </ol>
    </div>
</div>

<div class="container">


     <div class="row">
        <div class="col-lg-12 text-center">
          <h1><?php echo $this->translate('Réinitialisation de mot de passe ?'); ?></h1>
        </div>
      </div>
      <br>
      <div class="row" >
		<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-xs-12">
	        <form id="resetpassword-form" action="<?php echo $this->form->getAction()?>" method="post">
	        	<label for="email">Email :</label>
	         
				<div class="input-group text-center">
					<span class="input-group-addon"><i class="fa fa-user"></i></span>
					<input id="email" name="email" type="text" class="form-control" placeholder="<?php echo $this->translate('Entrez votre email') ?>"/>
				</div>
	          	<span class="">Il vous suffira de cliquer sur le lien envoyé dans l'email pour enregistrer un nouveau mot de passe.</span>
	          	<span class="help-block font-red"><?php if (isset($this->error)) {echo $this->translate($this->error);} ?></span>
	          	<div class="text-center">
	           		<button type="button" class="waiting btn btn-primary"><?php echo $this->translate('Réinitialiser mon mot de passe') ?></button>
	       		</div>
	        </form>


	      </div>
      </div>

      
    </div>
  </div>
</div>
<?php $this->headScript()->captureStart(); ?>
<?php if(false): ?><script><?php endif; ?>
$(document).ready(function() {

  $(".waiting").click(function(e) {
   

    // Vérification des champs
    if($("#email").val()==""){toastr.error("Veuillez renseigner votre Email");$("#email" ).focus();

      return;

    }else{

      //Envoie du formulaire
      $("#resetpassword-form").submit();

      // Toastr msg
      toastr.info('Envoie en cours ...');

    }
  });
});
<?php if(false): ?></script><?php endif; ?>
<?php $this->headScript()->captureEnd(); ?>