    <div class="container">
      <div class="row">

        <div class="confirmPage">

          <div class="row">
            <div class="col-lg-12 text-center">
              <?php if(!isset($this->error)){ ?>
                <h2 class=""><?php echo $this->translate('Votre compte est activé !'); ?></h2>
                <h3 class=" text-muted"><?php echo $this->translate('Découvrez sans attendre les nombreux projets de votre région et déposez-en également pour interagir avec vos voisins, amis, citoyens.'); ?></h3>
                <?php }else{ ?>
                <h2 class="error"><?php echo $this->translate('Votre compte est déjà activé !'); ?></h2>
                <?php } ?>
            </div>
          </div>
          
        </div>
      </div>
    </div>


