    <div class="container">
      <div class="row">

        <div class="confirmPage">

          <div class="row">
            <div class="col-lg-12 text-center">
              <h2 class=""><?php echo $this->translate('Un email vous a été envoyé !'); ?></h2>
              <h3 class=" text-muted"><?php echo $this->translate('Veuillez les vérifier et activer votre compte en cliquant sur le lien transmis.'); ?></h3>
              <br><p><?php echo $this->translate('Vous n\'avez pas reçu d\'email ? Vérifiez vos spams ou écrivez-nous : '); ?><a href="mailto:contact@citeez.fr">contact@citeez.fr</a></p>
            </div>
          </div>
          
        </div>
      </div>
    </div>


