<form action="/users/login" method="post">

	<?php if (isset($this->error['error'])) { ?>
	    <?php echo $this->error['error']; ?>
	<?php } ?>

	<?php if (isset($this->error['error-email'])) { ?>
	    <?php echo $this->error['error-email']; ?>
	<?php } ?>

	<?php if (isset($this->error['error-pwd'])) { ?>
	    <?php echo $this->error['error-pwd']; ?>
	<?php } ?>

    <div class="field">
        <label><?php echo $this->translate('E-mail') ?></label>
        <input type="text" name="email" />
    </div>
    <div class="field">
        <label><?php echo $this->translate('Password') ?></label>
        <input type="password" name="pwd" value="" />
    </div>

    <input type="submit" value="Connexion"/>

</form>
