<ol class="breadcrumb">
    <li><a href="/">Accueil</a></li>
    <?php if(isset($this->orga->domain)){ ?>
    	<li><a href="/<?php echo $this->orga->domain; ?>/projets"><?php echo $this->orga->domain; ?></a></li>
	    <li><a href="/<?php echo $this->orga->domain; ?>/projets">Projets</a></li>
    <?php }else{?>
    	<li><a href="/projets">Projets</a></li>
    <?php }?>


    <li><a href="/agit/cree-un-projet">Créer un projet</a></li>
    <li class="active">Projet envoyé</li>
</ol>

<div class="begin-project">

	<div class="section-header">
        <h2 class="section-heading">Félicitation !</h2>
        <h6>Vous venez de déposer un projet et devenez acteur de votre ville !</h6>
    </div>
</div>