<?php echo $this->partial('submenu-company.phtml'); ?>

<div id="main">

    <h3><?php echo $this->translate('Search Result') ?></h3>

    <ul class="company">

        <?php foreach($this->companies as $company) { ?>
        <li>
            <span class="state-<?php echo $company->state?>"></span>
            <div class="picture">
                <img src="<?php if (strlen($company->thumbnail) > 0) { echo $company->thumbnail; } else { echo '/assets/images/admin/company-no-picture.png'; } ?>" width="90" alt="" />
            </div>

            <div class="action">
                <a class="modify" href="<?php echo $this->link('companies', 'edit', array('id' => $company->id))?>"></a>
                <a class="delete fancy-delete" href="#delete" data-id="<?php echo $company->id?>" data-value="<?php $company->name?>" ></a>
            </div>

            <div class="text">
                <div class="name">
                    <?php echo $company->name ?>
                </div>
                <div class="contact">
                    <?php $admin = $company->getFirstAdmin(); ?>
                    <a class="fancy-email" href="#email" data-id="<?php $company->id?>" data-email="<?php echo $admin->email?>" title="Envoyer un e-mail"><?php echo $admin->email ?></a>
                </div>
            </div>

        </li>
        <?php } ?>
        <?php if (count($this->companies) == 0) { ?>
        <li>
            <?php echo $this->translate('No company yet') ?>
        </li>
        <?php } ?>
    </ul>

    <?php
    if (count($this->companies) > 0) {
        echo $this->paginationControl($this->companies, 'All', 'paginator.phtml');
    }
    ?>

</div>

<?php echo $this->partial('email-form.phtml')?>

<?php echo $this->partial('delete-form.phtml', array(
    'text' => 'Voulez-vous vraiment supprimer',
    'action' => $this->link('companies', 'delete'),
    'paramName' => 'id',
));?>