<div class="container">
	<div class="row">
      <!--left-->
      <div class="col-md-3" id="leftCol">
        <ul class="nav nav-stacked" id="sidebar">
	    	<li class="active"><a href="#sec0">A propos de Citeez</a>
			<li><a href="#sec1">L'équipe</a></li>
			<li><a href="#sec2">Presse</a></li>
        </ul>
      </div><!--/left-->
      
      <!--right-->
      <div class="col-md-9">
        <h2 id="sec0">A propos de Citeez</h2><br><br>
        <p>
          Citeez est une plateforme de partage entre citoyens.
			Notre volonté est de mettre à disposition des citoyens un outil simple et gratuit regroupant plusieurs fonctionnalités :
			<ul>
				<li>Création de projets ayant un impact local </li>
				<li>Dons et échanges de biens, services et compétences</li>
				<li>Débats citoyens</li>
				<li>Alertes citoyennes</li>
			</ul>
			
			
			
			</p>
        <hr>
        <p>
<span class="fa-stack fa-lg">
  <i class="fa fa-circle-o fa-stack-2x"></i>
  <i class="fa fa-lightbulb-o fa-stack-1x"></i>
</span>
          <b class=""> Création de projets</b><br><br>
L’objectif est de présenter vos projets personnels, associatifs ou professionnels ayant un impact local. Pourquoi local ? Tout simplement parce que nous pensons que ce sont les petites rivières qui font de grands fleuves. L’impact d’un projet local peut facilement être réitéré, repris, amélioré, amplifié. “Act” local, “think” global !<br>

Nous vous conseillons de porter un soin particulier à la rédaction de votre projet afin de le rendre lisible et compréhensible par le plus grand nombre.
Dans un second temps, vous pourrez le partager sur vos réseaux sociaux (Facebook, Twitter, LinkedIn, Viadeo).<br>
Votre projet bénéficiera des expériences et des idées de vos proches, amis, voisins pour le faire évoluer. Ils vous proposeront certainement une aide matérielle voire un soutien humain et/ou financier. <br>
En outre, l’équipe Citeez fera en sorte de remonter les initiatives locales les plus marquantes, intéressantes, ambitieuses aux collectivités locales concernées.
<br><br>
Soyez citoyens et faites appel à la solidarité !<br><br>

<span class="fa-stack fa-lg">
  <i class="fa fa-circle-o fa-stack-2x"></i>
  <i class="fa fa-thumb-tack fa-stack-1x"></i>
</span>
<b>Dons et échanges de biens, services et compétences</b><br><br>
Nous sommes entourés de ressources inexploitées alors que nous sommes habitués à consommer et à acheter de manière quasi compulsive. Pourtant, vos voisins ont certainement la tondeuse dont vous n’avez besoin que très ponctuellement ! Il a aussi peut-être l’appareil à raclette pour votre prochaine soirée.<br>
Au fait, puisque vous êtes bilingue, vous pouvez passer un moment agréable avec votre voisin en parlant anglais et l’aider ainsi à se perfectionner pour la promotion professionnelle qu’il envisage.<br>
Au passage, profitez-en pour donner les vêtements du petit dernier. Vous ferez des heureux qui vous le rendront au centuple !<br><br>

Sur Citeez, l’échange est notre seule monnaie !<br><br>

<span class="fa-stack fa-lg">
  <i class="fa fa-circle-o fa-stack-2x"></i>
  <i class="fa fa-university fa-stack-1x"></i>
</span>
<b>Débats citoyens</b><br><br>
De plus en plus de collectivités sont à l’écoute de leurs administrés. Les conseils de quartier se multiplient pour construire ensemble les nouveaux projets. <br>Pourtant, un outil est toujours nécessaire pour suivre l’évolution et interagir facilement et simplement sur ces débats.<br><br>

Citeez est le chaînon manquant de la citoyenneté positive. Faites-vous entendre de vos élus et participez à l’évolution des projets qui vous tiennent à coeur.<br><br>


<span class="fa-stack fa-lg">
  <i class="fa fa-circle-o fa-stack-2x"></i>
  <i class="fa fa-bullhorn fa-stack-1x"></i>
</span>
<b> Alertes citoyennes</b><br><br>
Une poubelle renversée, un éclairage défaillant, un panneau de signalisation abîmé, une dégradation de la chaussée, vous pouvez en informer rapidement les services publics concernés pour une action rapide.<br>
Cette fonctionnalité est développée conjointement avec les équipes de Fixmaville.</p>
        
  <br>
        <hr><br>

        <h2 id="sec1">L'équipe</h2><br><br>
        <p>
          Nous sommes 3 associés à mener Citeez. Déjà partenaires sur Troovon (une plateforme de consommation collaborative dédiée aux entreprises, comités d’entreprise, parcs d’affaires, etc), nous avons rapidement constaté les besoins des citoyens à échanger entre eux des biens, services et compétences. Au delà, le besoin de citoyenneté positive est partagé entre nous. <br><br>

Matthieu a longtemps participé à un Système d’Echanges local (SEL). Il est suffisamment fou pour construire sa maison tout seul avec l’aide de ses amis, de sa famille et de ses connaissances.<br><br>

Olivier, c’est notre porte étendard. Celui que vous verrez dans tous les médias … ou presque ! Il est convaincu que nous vivons une mutation économique et sociale et il fait la promotion de la consommation collaborative dès qu’il en a la possibilité. Il la transforme en acte en présentant Citeez et Troovon auprès de nos clients.<br><br>

Pour finir, Damien a rejoint l’aventure en 2014 pour organiser (quand il y arrive) les différents projets et idées de Matthieu et Olivier ! Convaincu que les énergies positives sont nombreuses et ne demandent qu’à s’exprimer, il partage son temps entre le pro, la famille et l’associatif. Il est effectivement très engagé au sein de la Jeune Chambre Economique Française depuis plusieurs années pour agir concrètement sur des projets locaux.
        </p>

        <br>
        <hr><br>
        
        <h2 id="sec2">Presse</h2>
        <p>
          En plein lancement, notre priorité est de faire évoluer nos services pour vous proposer une plateforme parfaite ! Malgré tout, si vous êtes séduit par Citeez, nous serons heureux que vous en disiez quelques mots sur votre média ! Pour nous contacter, c’est par ici

        </p>

        <br>
        <hr>

        </div><!--/right-->
  	</div><!--/row-->
</div><!--/container-->



<?php $this->headScript()->captureStart(); ?>
<?php if(false): ?><script><?php endif; ?>
$(document).ready(function() {

		/* activate sidebar */
$('#sidebar').affix({
  offset: {
    top: 235
  }
});

/* activate scrollspy menu */
var $body   = $(document.body);
var navHeight = $('.navbar').outerHeight(true) + 10;

$body.scrollspy({
	target: '#leftCol',
	offset: navHeight
});

/* smooth scrolling sections */
$('a[href*=#]:not([href=#])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html,body').animate({
          scrollTop: target.offset().top - 50
        }, 1000);
        return false;
      }
    }
});


	});
<?php if(false): ?></script><?php endif; ?>
<?php $this->headScript()->captureEnd(); ?>


