<div class="container">

	<h1>Associations</h1><br><br>
	<p>
Vous avez des projets pleins la tête et vous passez un temps fou à les promouvoir, les faire évoluer, les faire connaître. Les difficultés sont innombrables et on ne vous parle même pas des difficultés à trouver des financements !<br>
Citeez vous permet de mettre vos projets et votre mouvement en avant, de leur donner de la visibilité sur un outil consulté par les citoyens qui vous entourent, capables de vous donner un coup de main, de vous apporter une aide ponctuelle ou de s’engager à vos côtés.<br>
En outre, Citeez vous permettra de présenter vos projets à vos élus !<br><br>

Grâce à Citeez, donnez de l’ampleur à vos actions citoyennes locales et impactantes !
</p>
</div>