<div class="container">

 <h1>Conditions générales d'utilisation</h1>
 <article class="cms">
        <h3>1. Propriété intellectuelle</h3>
        <h4>1.1. Droits d'auteur et droits voisins </h4>
        <p>L'ensemble des éléments constituant le site Citeez.fr (textes, graphismes, logiciels, photographies, images, vidéos, sons, plans, noms, logos, marques, créations et œuvres protégeables diverses, bases de données, etc...) ainsi que le site lui-même, relèvent des législations françaises et internationales sur le droit d'auteur et sur les droits voisins du droit d'auteur (notamment les articles L122-4 et L122-5. du Code de la Propriété Intellectuelle). </p>
        <p>Ces éléments sont la propriété exclusive de “TROOVON SAS” hormis les éléments réalisés par des intervenants extérieurs au site Citeez.fr n'ayant pas cédé leurs droits d'auteur.</p>
        <p>En conséquence, l'utilisateur du site Citeez.fr s'engage à ne pas : </p>
        <ul>
            <li>utiliser ou interroger le site Citeez.fr pour le compte ou au profit d'autrui ; </li>
            <li>reproduire en nombre, à des fins commerciales ou non, des informations ou des petites annonces présentes sur le site Citeez.fr ; </li>
            <li>intégrer tout ou partie du contenu du site Citeez.fr dans un site tiers, à des fins commerciales ou non ; </li>
            <li>utiliser un robot, notamment d'exploration (spider), une application de recherche ou récupération de sites Internet ou tout autre moyen permettant de récupérer ou d'indexer tout ou partie du contenu du site Citeez.fr, excepté en cas d'autorisation expresse et préalable de TROOVON SAS ; </li>
            <li>copier les informations sur des supports de toute nature permettant de reconstituer tout ou partie des fichiers d'origine. </li>
        </ul>

        <p>Toute utilisation non expressément autorisée d'éléments du site Citeez.fr entraîne une violation des droits d'auteur et constitue une contrefaçon. Elle peut aussi entraîner une violation des droits à l'image, droits des personnes ou de tous autres droits et réglementations en vigueur. Elle peut donc engager la responsabilité civile et/ou pénale de son auteur. TROOVON SAS se réserve la possibilité de saisir toutes voies de droit à l'encontre des personnes qui n'auraient pas respecté les interdictions contenues dans le présent article.</p>

        <h4>1.2. Droits du producteur de base de données</h4>
        <p>TROOVON SAS est le producteur de la base de données constituée par le site Citeez.fr, au sens de l'article<br />
        L 341-1 et suivants du Code de la Propriété Intellectuelle. Toute extraction ou utilisation du contenu de la base non expressément autorisée peut engager la responsabilité civile et/ou pénale de son auteur. TROOVON SAS se réserve la possibilité de saisir toutes voies de droit à l'encontre des personnes qui n'auraient pas respecté cette interdiction. </p>
        <h4>1.3. Droit de marque</h4>
        <p>Les dénomination et logotype CITEEZ sont des marques déposées, propriété de TROOVON SAS. Toute utilisation non expressément autorisée peut engager la responsabilité civile et/ou pénale de son auteur. TROOVON SAS se réserve la possibilité d'exercer toutes voies de droit à l'encontre des personnes qui porteraient atteinte à ses droits. </p>
        <h3>2. Protection des données personnelles</h3>
        <p>Conformément à la loi n°78-17 du 6 janvier 1978, dite « Informatique et libertés », TROOVON SAS  a fait l'objet d'une déclaration auprès de la Commission Nationale de l'Informatique et des Libertés (C.N.I.L). Conformément à l'article 27 de la loi n°78-17 du 6 janvier 1978, vous disposez à tout moment d'un droit d'accès et de rectification des données vous concernant. Ce droit peut être exercé par courrier postal ou courrier électronique (mél) auprès de TROOVON SAS : </p>
        <p>Adresse : TROOVON SAS - : 21 av du Patis Vert, 44120 Vertou / ou par email : contact@troovon.com<br>
        Le numéro de déclaration CNIL est : 1619123 v 0<br>
        </p>
        <h3>3. Responsabilités </h3>
        <p>TROOVON SAS décline toute responsabilité:</p>
        <ul>
            <li>en cas d'interruption de Citeez.fr pour des opérations de maintenance techniques ou d'actualisation des informations publiées, </li>
            <li>en cas d'impossibilité momentanée d'accès à Citeez.fr (et/ou aux sites lui étant liés) en raison de problèmes techniques et ce quelles qu'en soient l'origine et la provenance, </li>
            <li>en cas de dommages directs ou indirects causés à l'utilisateur, quelle qu'en soit la nature, résultant du contenu, de l'accès, ou de l'utilisation de Citeez.fr (et/ou des sites qui lui sont liés), </li>
            <li>en cas d'utilisation anormale ou d'une exploitation illicite de Citeez.fr. L'utilisateur de Citeez.fr est alors seul responsable des dommages causés aux tiers et des conséquences des réclamations ou actions qui pourraient en découler. L'utilisateur renonce également à exercer tout recours contre TROOVON SAS dans le cas de poursuites diligentées par un tiers à son encontre du fait de l'utilisation et/ou de l'exploitation illicite du site, y compris des offres de partenaires, </li>
            <li>en cas de perte par le membre de Citeez.fr de son identifiant et/ou de son mot de passe ou en cas d'usurpation de son identité. </li>
        </ul>
        <h3>4. Liens hypertexte</h3>
        <h4>4.1. Liens à partir du site Citeez.fr</h4>
        <p>Le site Citeez.fr peut contenir des liens hypertextes vers des sites exploités par des tiers. Ces liens sont fournis à simple titre d'information. TROOVON SAS n'exerce aucun contrôle sur ces sites et décline toute responsabilité quant à l'accès, au contenu ou à l'utilisation de ces sites, ainsi qu'aux dommages pouvant résulter de la consultation des informations présentes sur ces sites. La décision d'activer ces liens relève de la pleine et entière responsabilité de l'internaute. </p>
        <h4>4.2. Liens vers le site Citeez.fr</h4>
        <p>Des liens hypertexte peuvent être crées vers le site Citeez.fr sans l'accord préalable de TROOVON SAS, cependant TROOVON SAS se réserve le droit d’en demander le retrait immédiat sans avoir à en justifier la raison.</p>
               <h3>5. Cookies</h3>
        <p>Afin de faciliter la navigation sur le site Citeez.fr, des cookies peuvent être implantés dans votre ordinateur afin par exemple de conserver les critères de recherche.
        Si vous ne souhaitez pas accepter l'implantation de cookies vous pouvez régler votre navigateur afin de les refuser. Cependant, l'utilisation de Citeez.fr peut en être perturbée. </p>
        <h3>6. Modifications des Conditions Générales d'Utilisation</h3>
        <p>TROOVON SAS se réserve le droit de modifier, librement et à tout moment, les Conditions Générales d'Utilisation du site Citeez.fr. Chaque internaute se connectant au site Citeez.fr est invité à consulter régulièrement les présentes conditions d'utilisation afin de prendre connaissance de changements éventuels. L'utilisation renouvelée du site au fur et à mesure de la modification de ces conditions d'utilisation constitue l'acceptation, par chaque utilisateur, des Conditions Générales d'Utilisation en vigueur. </p>
        <h3>7. Attribution de juridiction – Loi applicable</h3>
        <p>Toutes contestations qui pourraient survenir au sujet de la validité, de l'interprétation, de l'acceptation et de l'exécution des présentes quel que soit le lieu de souscription, ou de règlement, feront l'objet d'une tentative de règlement amiable que les parties s'engagent à rechercher. </p>
        <p>Les présentes conditions générales sont soumises au droit français, qui détermine, au cas par cas, la loi applicable. </p>

        <h2>Conditions générales de diffusion</h2>

        <h3>1. Acceptation des conditions générales de diffusion</h3>
        <p>1.1 La diffusion d’une action (ci-après « Action ») diffusée sur le site internet www.citeez.fr édité par la société TROOVON SAS, implique pour l'auteur de l’Action, l'acceptation sans réserve des présentes conditions générales de diffusion à l'exclusion expresse de toutes conditions autres ou contraires des co-contractants de TROOVON SAS, insérées dans leurs documents d'information, lettres, contrats, etc., reçus ou à recevoir et de tous usages professionnels contraires aux présentes, lesquels conditions et usages seront considérés comme inopposables à TROOVON SAS.</p>
        <p>1.2 Toute adjonction, rature, modification ou suppression qui serait portée sur les présentes devra, pour être opposable à TROOVON SAS être contresignées par celle-ci.</p>
        <p>1.3 Le fait que TROOVON SAS ne se prévale pas à un moment donné de l'une quelconque des dispositions des présentes conditions générales de diffusion ne peut être interprété comme valant renonciation à s'en prévaloir ultérieurement.</p>

        <h3>2. Diffusion</h3>
        <p>2.1 L'annonceur reconnaît être l'auteur unique et exclusif du texte de l'Action (projet ou annonce). A défaut, il déclare disposer de tous les droits et autorisations nécessaires à la parution de l'Action.</p>
        <p>2.2 L'Action est diffusée sous la responsabilité exclusive de l'annonceur. L’Action peut prendre la forme d’un projet ou d’une petite annonce qui sera publiée sur le site Citeez.fr</p>
        <p>2.3 L'auteur de l’Action certifie que l'Action est conforme à l'ensemble des dispositions légales et réglementaires en vigueur et respecte les droits des tiers. En conséquence, l'annonceur relève TROOVON SAS, ses sous-traitants et fournisseurs, de toutes responsabilités, et les garantit contre toutes condamnations, frais judiciaires et extrajudiciaires, qui résulteraient de tout recours en relation avec la diffusion de l'Action et les indemnise pour tout dommage résultant de la violation de la présente disposition.</p>
        <p>2.4 Sans préjudice de l'application de la précédente clause, et sans que cela crée à sa charge une obligation de vérifier le contenu, l'exactitude ou la cohérence de l'Action, TROOVON SAS se réserve le droit de supprimer à tout moment une Action pour tout motif légitime, et notamment des éléments de texte (mots, expressions, phrases…etc.), qui lui semblerait contraire aux dispositions légales ou réglementaires, aux bonnes mœurs, à l'esprit de la publication, ou susceptible de troubler ou choquer les lecteurs. Un tel refus ne fait naître au profit de l'auteur de l’Action aucun droit à indemnité.</p>

        <h3>3. Limitation de responsabilité</h3>
        <p>3.1 Sauf dol ou faute lourde, TROOVON SAS, ses sous-traitants et fournisseurs ne seront tenus en aucun cas à réparation, pécuniaire ou en nature, du fait d'erreurs ou d'omissions dans la composition ou la traduction d'une Action, ou de défaut de parution de quelque nature que ce soit. En particulier, de tels événements ne pourront en aucun cas ouvrir droit à une indemnisation sous quelque forme que ce soit.</p>
        <p>3.2 Ni l'auteur de l’Action, d'une part, ni TROOVON SAS, ses sous-traitants ou fournisseurs, d'autre part, ne pourra être tenu pour responsable de tout retard, inexécution ou autre manquement à ses obligations au titre des présentes qui (1) résulterait, directement ou indirectement, d'un événement échappant à son contrôle raisonnable, et (2) n'aurait pas pu être évité à l'aide de mesures de précaution, solutions de remplacement ou autres moyens commercialement raisonnables.</p>
        <p>3.3 Ni l'auteur de l’Action, d'une part, ni TROOVON SAS, ses sous-traitants ou fournisseurs, d'autre part, ne pourra être tenu pour responsable des retards ou des impossibilités de remplir ses obligations contractuelles, liés à des destructions de matériels, aux attaques ou aux piratages informatiques, à la privation, à la suppression ou à l'interdiction, temporaire ou définitive, et pour quelque cause que ce soit - dont les pannes ou indisponibilités inhérentes aux serveurs d'hébergement -, de l'accès au réseau Internet.</p>
        <p>3.4 TROOVON SAS se réserve le droit de suspendre ou d'arrêter la diffusion du site www.citeez.fr sans être tenue de verser à l'auteur de l’Action une indemnité de quelque nature que ce soit.</p>
        <p>3.5 Toute réclamation, pour être recevable, doit être transmise par lettre simple, télécopie ou e-mail, dans un délai de quarante-huit (48) heures à compter de la date de diffusion sur www.citeez.fr.</p>

        <h3>4. Attribution de juridiction – Loi applicable</h3>
        <p>4.1 Toutes contestations qui pourraient survenir à l'occasion de l'interprétation, de l'acceptation et de l'exécution des présentes quel que soit le lieu de souscription, ou de règlement, feront l'objet d'une tentative de règlement amiable que les parties s'engagent à rechercher. </p>
        <p>4.2 Les présentes conditions générales sont soumises à la loi française. </p>

        <h3>5. Divers</h3>
        <p>5.1 Les marques et logotypes CITEEZ sont déposés par TROOVON SAS. Sans l'accord de cette dernière, toute reproduction ou utilisation est strictement interdite. </p>

    </article>





</div>