<div class="container">

	<h1>Collectivités</h1><br><br>
	<p>
La décentralisation donne de plus en plus de pouvoirs (et de contraintes) aux collectivités locales. Les citoyens souhaitent participer aux débats d’une manière réinventée.<br>
Citeez s’adresse à vous pour mettre à disposition de vos administrés un outil simple d’échanges et de partages.<br>
De votre côté, vous pourrez alimenter vos réflexions pour proposer des évolutions co-construites avec eux. Vous prendrez connaissance de projets émanant de votre territoire et impulserez une intelligence collective bénéfique à votre cité.<br>
Vous disposerez également d’un espace reprenant de nombreuses informations vous permettant de mieux piloter votre collectivité.<br><br>

Vous êtes intéressés, vous souhaitez en savoir plus ? Contactez-nous dès maintenant !
</p>
</div>