<div class="container">

 <h1>Informations légales</h1>

    <article class="cms">
        <p>(conformément à la LOI n°2004-275 pour la Confiance dans l’Économie)<br />
        “Citeez” by “TROOVON SAS” (société par actions simplifiée)<br />
        Editorial Staff: Matthieu Charron / Olivier Tizio / Damien Durrleman
        </p>
        <p>
        Le site Internet www.citeez.fr, ci-après dénommé « Citeez » propose un service de partage et d’entraide entre citoyens avec la possibilité de déposer et de consulter des projets et des petites annonces sur Internet en mode SaaS (Logiciel en tant que service) et est plus spécifiquement destiné aux particuliers et eux Collectivités.
        <br />
        L'accès au site, sa consultation et son utilisation sont subordonnés à l'acceptation sans réserve des présentes Conditions Générales d'Utilisation de Citeez.fr. <br />
        <br />
        Le site web www.citeez.fr est édité par TROOVON, SAS au capital de 2.000 euros, immatriculée au registre du commerce et des sociétés de Nantes. <br />
        </p>
        <h3>Siège social </h3>
        <ul>
            <li>”TROOVON SAS” 21 av du Patis Vert, 44120 Vertou</li>
            <li>Le Directeur de Publication de Citeez.fr est Monsieur Matthieu CHARRON. </li>

        </ul>
        <p>
        Intercommunity VAT number : FR2975202668200019
        </p>
        <p>Pour toute question sur l'entreprise, vous pouvez nous <strong>envoyer vos questions par email</strong>. </p>
        <h3>1 – Informations :</h3>
        <p>
        Les informations publiées, y compris dans leur aspect et leurs caractéristiques, sur le site internet www.citeez.fr sont non contractuelles. </p>
        <p>Ces informations ne constituent en aucun cas une assertion, une garantie ou un quelconque engagement de la part de www.citeez.fr à l’égard de tout produit ou service : www.citeez.fr décline toute responsabilité, expresse ou implicite, quant à leur complétude, leur exactitude ou leur adéquation à un but quelconque. </p>
        <p>www.citeez.fr a fait tous ses efforts pour s’assurer que les informations accessibles par l’intermédiaire de son site web sont exactes. Cependant, nous ne garantissons en aucune manière que ces informations soient exactes, complètes et à jour. </p>
        <p>www.citeez.fr n’assure aucune garantie, expresse ou tacite, concernant tout ou partie de son site web. En aucun cas, www.citeez.fr ne peut être tenu pour responsable d’un quelconque dommage direct ou indirect, quelle qu’en soit la nature, découlant de l’utilisation de son site web.
        La mise en place de liens hypertextes en direction d’autres sites ou de ressources disponibles sur le réseau Internet, ne saurait engager la responsabilité de www.citeez.fr ni celle de son hébergeur à raison des contenus proposés par les sites désignés. </p>
        <p>Troovon SAS décline toute responsabilité concernant le contenu de sites liés au site web de www.citeez.fr . <br />
        www.citeez.fr décline toutes responsabilités quant à la pertinence des informations fournies et à l’utilisation qu’un internaute est susceptible d’en faire. <br />
        </p>
        <h3>2 – Modifications :</h3>
        <p>
        www.citeez.fr se réserve le droit de modifier ou de corriger, à tout moment et sans préavis, les contenus de son site internet, quelle que soit leur nature. </p>
        <h3>3 – Droits d’auteur – Copyright</h3>
        <p>L’ensemble de ce site relève de la législation française et internationale sur le droit d’auteur et la propriété intellectuelle. Tous les droits de reproduction sont réservés, y compris les documents téléchargeables et les représentations photographiques. La reproduction de tout ou partie de ce site sur un support, quel qu’il soit, est formellement interdite, sauf autorisation expresse du responsable de la rédaction. </p>
	<p>Crédit photos : La photo de la page d’accueil de www.citeez.fr a été trouvée sur google avec le filtre “Utilisation et modification autorisée”. Cette photo provient du site web suivant : https://istanbulcityportrait.wordpress.com/key-dates-and-venues/city-culture/aldo-cibic/ <br />

        <h3>4 – Hébergement</h3>
        <p>Le site internet de CITEEZ (www.citeez.fr) est hébergé par : <br />
        SAS OVH<br />
        RCS Roubaix – Tourcoing 424 761 419 00045<br />
        Code APE 6202A<br />
        N° TVA : FR 22 424 761 419<br />
        Siège social : 2 rue Kellermann - 59100 Roubaix - France. <br />
        Support Technique : 08.99.70.17.61 ( 1.349 Euro/appel + 0.337 Euro/min) <br />
        Support Commercial : 08.20.32.03.63 (Numéro Indigo 0.118 Euro/min) <br />
        Fax : 03.20.20.09.58</p>
    </article>

</div>