<div class="container">

	<h1>Partenaires</h1><br><br>
	<p>
On en a des idées chez Citeez … beaucoup ! Grâce à nos expériences passées nous bénéficions d’un important réseau de partenaires dans le secteur de la consommation collaborative.<br>
Nous savons que c’est ensemble que nous arriverons à démocratiser et à réellement faire connaître et utiliser ces services par le plus grand nombre. Citeez est donc ouvert à toutes les initiatives intéressantes permettant de donner et échanger entre particuliers.<br>
Pour commencer, nous avons envie de créer des synergies avec des acteurs agissant dans les domaines suivants :<br>
<ul>
<li>Covoiturage local</li>
<li>Echanges/dons de vêtements entre particuliers</li>
<li>Partage de compétences</li>
</ul>
<br>
Contactez-nous, c’est sur que nous avons des choses à faire ensemble !<br><br>

Tout seul, on va plus vite, Ensemble, on va plus loin....plus vite ! <br>
(paraphrase d’un proverbe africain bien connu ...qu’on adore !)
</p>
</div>