
<div class="container">

	<div class="row searchpage">

		<?php
		foreach ($this->projects as $project) {
			?>
        	<div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
           		<div itemscope="" itemtype="http://schema.org/Enumeration" class="col-6 row-space-1 maindivproject searchdivproject">
           
					<?php echo $this->partial('one-project.phtml', array('project' => $project)); ?>

            </div>
        </div>
		<?php } ?>
	</div>
</div>