<?php

/**
 * Model_CzMedia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_CzMedia extends Model_Entity_CzMedia
{

    public function getThumb($width = '250', $height = '250') {


        $config = Zend_Registry::get('config');
        $url_media=$config->url_media;
        $url_web_media=$config->url_web_media;

        // Authorized sizes
        $sizes = array(
            array('w' => '800', 'h' => '600'),
            array('w' => '250', 'h' => '250'),
            array('w' => '520', 'h' => '390'),
            array('w' => '400', 'h' => '300'),
            array('w' => '350', 'h' => '265'),
            array('w' => '300', 'h' => '225'),
            array('w' => '200', 'h' => '150'),
            array('w' => '80', 'h' => '80'),
            array('w' => '30', 'h' => '30')
        );
        if (!in_array(array('w' => $width, 'h' => $height), $sizes)) {
            return;
        }
        // --

        $root = $url_media;
        $folders = substr($this->name, 0, 1).'/'.substr($this->name, 1, 1).'/'.substr($this->name, 2, 1).'/';

        if (!file_exists($root.$folders.$this->name.'-'.$width.'-'.$height.'.jpg') && file_exists($root.$folders.$this->name.'.jpg')) {

            $ImageChoisie = imagecreatefromjpeg($root.$folders.$this->name.'.jpg');
            $TailleImageChoisie = getimagesize($root.$folders.$this->name.'.jpg');
            $NouvelleLargeur = $width; 

            $NouvelleHauteur = ( ($TailleImageChoisie[1] * (($NouvelleLargeur)/$TailleImageChoisie[0])) );

            $NouvelleImage = imagecreatetruecolor($NouvelleLargeur , $NouvelleHauteur) or die ("Erreur");

            imagecopyresampled($NouvelleImage , $ImageChoisie  , 0,0, 0,0, $NouvelleLargeur, $NouvelleHauteur, $TailleImageChoisie[0],$TailleImageChoisie[1]);
            imagedestroy($ImageChoisie);
            $NomImageChoisie = explode('.', $ImageNews);
            $NomImageExploitable = $root.$folders.$this->name.'-'.$width.'-'.$height.'.jpg';

            imagejpeg($NouvelleImage , $NomImageExploitable, 100);
            $LienImageNews = $NomImageExploitable;

        }

        // Retourne cached picture
        return $url_web_media.$folders.$this->name.'-'.$width.'-'.$height.'.jpg';
    }
}